//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArtPlanning.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class folder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public folder()
        {
            this.mission = new HashSet<mission>();
        }
    
        public int id { get; set; }
        public int client_id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public string customer_name { get; set; }
        public Nullable<System.DateTime> added_date { get; set; }
        public string added_user { get; set; }
        public Nullable<System.DateTime> modification_date { get; set; }
        public string modification_user { get; set; }
        public Nullable<bool> closed { get; set; }
        public Nullable<System.DateTime> closed_date { get; set; }
        public string closed_user { get; set; }
        public string customer_phone { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mission> mission { get; set; }
    }
}
