//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArtPlanning.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class task
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public task()
        {
            this.task_material = new HashSet<task_material>();
            this.task_service = new HashSet<task_service>();
            this.task_staff = new HashSet<task_staff>();
            this.task_vehicle = new HashSet<task_vehicle>();
        }
    
        public int id { get; set; }
        public int mission_id { get; set; }
        public Nullable<int> task_type_id { get; set; }
        public Nullable<int> address_id { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public Nullable<System.DateTime> scheduled_start_date { get; set; }
        public Nullable<System.DateTime> scheduled_end_date { get; set; }
        public Nullable<System.DateTime> arrival_date { get; set; }
        public Nullable<System.DateTime> departure_date { get; set; }
        public Nullable<int> arrival_mileage { get; set; }
        public Nullable<int> departure_mileage { get; set; }
        public Nullable<bool> day { get; set; }
        public Nullable<bool> @fixed { get; set; }
        public string comment { get; set; }
        public Nullable<System.DateTime> added_date { get; set; }
        public string added_user { get; set; }
        public Nullable<System.DateTime> modification_date { get; set; }
        public string modification_user { get; set; }
        public Nullable<bool> sql_modified { get; set; }
        public Nullable<bool> sql_deleted { get; set; }
        public string report { get; set; }
    
        public virtual address address { get; set; }
        public virtual mission mission { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<task_material> task_material { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<task_service> task_service { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<task_staff> task_staff { get; set; }
        public virtual task_type task_type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<task_vehicle> task_vehicle { get; set; }
    }
}
