//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArtPlanning.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class translate_vehicle
    {
        public int id { get; set; }
        public int language_id { get; set; }
        public int vehicle_id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
    
        public virtual language language { get; set; }
        public virtual vehicle vehicle { get; set; }
    }
}
